name: dhn-predict
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  # BLAS variant (optional, same notes as above)
  # - libblas=*=*openblas
  # - libblas=*=*openblas_ilp64
  - pip:
      - torch==1.13.1
      - numpy<2
      - scipy
      - pandas
      - scikit-learn
      - jupyterlab
      - matplotlib
      - tqdm
      - pyyaml
      - optuna
      - statsmodels
      - properscoring
